version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directories:
      - /tabletest-parser
      - /tabletest-junit
    schedule:
      interval: weekly
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      junit:
        patterns:
          - "org.junit*"

  - package-ecosystem: maven
    directories:
      - /compatibility-tests/basic/maven-java
      - /compatibility-tests/basic/maven-kotlin
      - /compatibility-tests/basic-java8/maven-java
      - /compatibility-tests/frameworks/maven-quarkus-java
      - /compatibility-tests/frameworks/maven-springboot-java
    schedule:
      interval: weekly
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
    ignore:
      - dependency-name: "org.junit.jupiter:*"
      - dependency-name: "org.junit:*"
      - dependency-name: "org.junit.platform:*"
      - dependency-name: "io.quarkus:*"
      - dependency-name: "io.quarkus.platform:*"
      - dependency-name: "org.springframework.boot:*"

  - package-ecosystem: gradle
    directories:
      - /compatibility-tests/basic/gradle-java
      - /compatibility-tests/basic/gradle-kotlin
      - /compatibility-tests/basic-java8/gradle-java
      - /compatibility-tests/frameworks/gradle-quarkus-kotlin
      - /compatibility-tests/frameworks/gradle-springboot-kotlin
    schedule:
      interval: weekly
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
    ignore:
      - dependency-name: "org.junit.jupiter:*"
      - dependency-name: "org.junit:*"
      - dependency-name: "org.junit.platform:*"
      - dependency-name: "io.quarkus:*"
      - dependency-name: "io.quarkus.platform:*"
      - dependency-name: "org.springframework.boot:*"
